Avro C++: avro::GenericEnum Class Reference
avro::GenericEnum Class Reference
Generic container for Avro enum.
#include <Generic.hh>