// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nested_enum.proto

package org.apache.avro.protobuf.cornucopia.v1;

public final class NestedEnumOuterClass {
  private NestedEnumOuterClass() {
  }

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public interface SomeOuterMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cornucopia.v1.SomeOuterMessage)
      com.google.protobuf.MessageOrBuilder {
  }

  /**
   * Protobuf type {@code cornucopia.v1.SomeOuterMessage}
   */
  public static final class SomeOuterMessage extends com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cornucopia.v1.SomeOuterMessage)
      SomeOuterMessageOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use SomeOuterMessage.newBuilder() to construct.
    private SomeOuterMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private SomeOuterMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({ "unused" })
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
      return new SomeOuterMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return this.unknownFields;
    }

    private SomeOuterMessage(com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.internal_static_cornucopia_v1_SomeOuterMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
      return org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.internal_static_cornucopia_v1_SomeOuterMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage.class,
              org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage.Builder.class);
    }

    /**
     * <pre>
     * Enum named as camel case version of the file name
     * </pre>
     *
     * Protobuf enum {@code cornucopia.v1.SomeOuterMessage.NestedEnum}
     */
    public enum NestedEnum implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>FOO = 0;</code>
       */
      FOO(0),
      /**
       * <code>BAR = 1;</code>
       */
      BAR(1),
      /**
       * <code>BAZ = 2;</code>
       */
      BAZ(2), UNRECOGNIZED(-1),;

      /**
       * <code>FOO = 0;</code>
       */
      public static final int FOO_VALUE = 0;
      /**
       * <code>BAR = 1;</code>
       */
      public static final int BAR_VALUE = 1;
      /**
       * <code>BAZ = 2;</code>
       */
      public static final int BAZ_VALUE = 2;

      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException("Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static NestedEnum valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static NestedEnum forNumber(int value) {
        switch (value) {
        case 0:
          return FOO;
        case 1:
          return BAR;
        case 2:
          return BAZ;
        default:
          return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<NestedEnum> internalGetValueMap() {
        return internalValueMap;
      }

      private static final com.google.protobuf.Internal.EnumLiteMap<NestedEnum> internalValueMap = new com.google.protobuf.Internal.EnumLiteMap<NestedEnum>() {
        public NestedEnum findValueByNumber(int number) {
          return NestedEnum.forNumber(number);
        }
      };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException("Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }

      public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
        return getDescriptor();
      }

      public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
        return org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage.getDescriptor()
            .getEnumTypes().get(0);
      }

      private static final NestedEnum[] VALUES = values();

      public static NestedEnum valueOf(com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException("EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private NestedEnum(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:cornucopia.v1.SomeOuterMessage.NestedEnum)
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1)
        return true;
      if (isInitialized == 0)
        return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1)
        return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage)) {
        return super.equals(obj);
      }
      org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage other = (org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage) obj;

      if (!unknownFields.equals(other.unknownFields))
        return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage parseFrom(
        java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage parseFrom(
        java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage parseFrom(
        com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage parseFrom(
        com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage parseFrom(byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage parseFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage parseFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage parseDelimitedFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage parseDelimitedFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage parseFrom(
        com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage parseFrom(
        com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(
        org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code cornucopia.v1.SomeOuterMessage}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cornucopia.v1.SomeOuterMessage)
        org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.internal_static_cornucopia_v1_SomeOuterMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.internal_static_cornucopia_v1_SomeOuterMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage.class,
                org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage.Builder.class);
      }

      // Construct using
      // org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
        }
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.internal_static_cornucopia_v1_SomeOuterMessage_descriptor;
      }

      @java.lang.Override
      public org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage getDefaultInstanceForType() {
        return org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage.getDefaultInstance();
      }

      @java.lang.Override
      public org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage build() {
        org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage buildPartial() {
        org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage result = new org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage(
            this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
          java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage) {
          return mergeFrom((org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage other) {
        if (other == org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage.getDefaultInstance())
          return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage) e
              .getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }

      // @@protoc_insertion_point(builder_scope:cornucopia.v1.SomeOuterMessage)
    }

    // @@protoc_insertion_point(class_scope:cornucopia.v1.SomeOuterMessage)
    private static final org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage();
    }

    public static org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SomeOuterMessage> PARSER = new com.google.protobuf.AbstractParser<SomeOuterMessage>() {
      @java.lang.Override
      public SomeOuterMessage parsePartialFrom(com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SomeOuterMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SomeOuterMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SomeOuterMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.apache.avro.protobuf.cornucopia.v1.NestedEnumOuterClass.SomeOuterMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor internal_static_cornucopia_v1_SomeOuterMessage_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_cornucopia_v1_SomeOuterMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
  static {
    java.lang.String[] descriptorData = { "\n\021nested_enum.proto\022\rcornucopia.v1\";\n\020So"
        + "meOuterMessage\"\'\n\nNestedEnum\022\007\n\003FOO\020\000\022\007\n"
        + "\003BAR\020\001\022\007\n\003BAZ\020\002B(\n&org.apache.avro.proto" + "buf.cornucopia.v1b\006proto3" };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {});
    internal_static_cornucopia_v1_SomeOuterMessage_descriptor = getDescriptor().getMessageTypes().get(0);
    internal_static_cornucopia_v1_SomeOuterMessage_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cornucopia_v1_SomeOuterMessage_descriptor, new java.lang.String[] {});
  }

  // @@protoc_insertion_point(outer_class_scope)
}
