on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

name: Clippy Check

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --all-targets -- -Dclippy::all -Dunused_imports
