# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

FROM debian:stable

WORKDIR /root/quicklisp/local-projects/avro/

COPY avro.asd ./
COPY src ./src
COPY test ./test

RUN apt-get update && apt-get install -y --no-install-recommends \
    sbcl cl-quicklisp \
    && sbcl --noinform --end-runtime-options \
            --no-sysinit --no-userinit \
            --load $(find / -name 'quicklisp.lisp' -type f) \
            --non-interactive \
            --eval '(declaim (optimize (debug 3) (safety 3)))' \
            --eval '(quicklisp-quickstart:install)' \
            --eval '(ql:quickload :avro/test)' \
            --eval '(sb-ext:save-lisp-and-die \
                      "test-image" \
                      :toplevel (lambda () \
                                  (asdf:test-system :avro)))' \
            --end-toplevel-options \
    && mkdir /app \
    && mv ./test-image /app/test-image

CMD ["sbcl", "--noinform", "--core", "/app/test-image"]
