// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Avro.Test.Generic.Autogen
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class HeaderDTO : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"HeaderDTO\",\"namespace\":\"Avro.Test.Generic.Autogen\",\"fiel" +
				"ds\":[{\"name\":\"Info\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"InfoDto\",\"namespace\"" +
				":\"Avro.Test.Generic.Autogen\",\"fields\":[{\"name\":\"Count\",\"type\":\"int\"}]}]}]}");
		private Avro.Test.Generic.Autogen.InfoDto _Info;
		public virtual Schema Schema
		{
			get
			{
				return HeaderDTO._SCHEMA;
			}
		}
		public Avro.Test.Generic.Autogen.InfoDto Info
		{
			get
			{
				return this._Info;
			}
			set
			{
				this._Info = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Info;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Info = (Avro.Test.Generic.Autogen.InfoDto)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
