package test;
/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/**  */
@org.apache.avro.specific.AvroGenerated
public class Dummy extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 554708886178016208L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Dummy\",\"namespace\":\"test\",\"doc\":\"\",\"fields\":[{\"name\":\"stringField\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence stringField;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Dummy() {}

  /**
   * All-args constructor.
   * @param stringField The new value for stringField
   */
  public Dummy(java.lang.CharSequence stringField) {
    this.stringField = stringField;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return stringField;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: stringField = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'stringField' field.
   * @return The value of the 'stringField' field.
   */
  public java.lang.CharSequence getStringField() {
    return stringField;
  }


  /**
   * Creates a new Dummy RecordBuilder.
   * @return A new Dummy RecordBuilder
   */
  public static test.Dummy.Builder newBuilder() {
    return new test.Dummy.Builder();
  }

  /**
   * Creates a new Dummy RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Dummy RecordBuilder
   */
  public static test.Dummy.Builder newBuilder(test.Dummy.Builder other) {
    return new test.Dummy.Builder(other);
  }

  /**
   * Creates a new Dummy RecordBuilder by copying an existing Dummy instance.
   * @param other The existing instance to copy.
   * @return A new Dummy RecordBuilder
   */
  public static test.Dummy.Builder newBuilder(test.Dummy other) {
    return new test.Dummy.Builder(other);
  }

  /**
   * RecordBuilder for Dummy instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Dummy>
    implements org.apache.avro.data.RecordBuilder<Dummy> {

    private java.lang.CharSequence stringField;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(test.Dummy.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.stringField)) {
        this.stringField = data().deepCopy(fields()[0].schema(), other.stringField);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Dummy instance
     * @param other The existing instance to copy.
     */
    private Builder(test.Dummy other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.stringField)) {
        this.stringField = data().deepCopy(fields()[0].schema(), other.stringField);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'stringField' field.
      * @return The value.
      */
    public java.lang.CharSequence getStringField() {
      return stringField;
    }

    /**
      * Sets the value of the 'stringField' field.
      * @param value The value of 'stringField'.
      * @return This builder.
      */
    public test.Dummy.Builder setStringField(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.stringField = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'stringField' field has been set.
      * @return True if the 'stringField' field has been set, false otherwise.
      */
    public boolean hasStringField() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'stringField' field.
      * @return This builder.
      */
    public test.Dummy.Builder clearStringField() {
      stringField = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public Dummy build() {
      try {
        Dummy record = new Dummy();
        record.stringField = fieldSetFlags()[0] ? this.stringField : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
